### ISSUE TITLE
Error when calculating the sum of an empty array

### ISSUE THREAD

**Issue by Gizeta** [magicae/rubist#1]
`TypeError: reduce of empty array with no initial value`
It seems that no initial value was provided when using reduce function.
___
There is a way to define a new property directly on an object.
``` javascript
Object.defineProperty(Array.prototype, "sum", {
  get: function(){
    return this.reduce((a, b) => a + b, 0);
  }
});
```
So we can use `[1,2,3].sum` without parenthesis. Do you think which one is better?

**Comment by magicae** [comment]
+ Is it ok to set initial value to `0`?
+ It sounds better to use getter for a function which named as a noun. I'll modify this api.

**Comment by Gizeta** [comment]
I tried `[].sum` in Rails, it return `0`. And the value of any empty sum in mathematics is zero. So I think it is ok.
But, when using sum on arrays of strings, the initial value should be `""`. Maybe you should detect the type first.
